//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani_proje_Sonn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Oto_GaleriEntities : DbContext
    {
        public Oto_GaleriEntities()
            : base("name=Oto_GaleriEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alım> Alım { get; set; }
        public virtual DbSet<Arac> Arac { get; set; }
        public virtual DbSet<Müsteri> Müsteri { get; set; }
        public virtual DbSet<Satıs> Satıs { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
