//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Veritabani_proje_Sonn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satıs
    {
        public int satno { get; set; }
        public Nullable<int> mno { get; set; }
        public Nullable<int> aracno { get; set; }
        public Nullable<System.DateTime> sat_tarih { get; set; }
        public decimal sfiyat { get; set; }
    
        public virtual Arac Arac { get; set; }
        public virtual Müsteri Müsteri { get; set; }
    }
}
